### ISSUE TITLE
Vertalingen nodig voor aangepaste alt-tekst logo

### ISSUE THREAD

**Issue by anneke** [minvws/nl-covid19-notification-app-website#405]
```yml
govlogo:
  nl: Logo Rijksoverheid, homepage // correct
  en: Logo Dutch Government, homepage // correct
  ar: الصفحة الرئيسية
  bg: Начална страница
  de: Home
  es: Inicio
  fr: Accueil
  pl: Strona główna
  ro: Pagina inițială
  tr: Anasayfa

header__logo-badge: 
  nl: Logo CoronaMelder app
  en: Logo CoronaMelder app // correct
  ar: 
  bg: 
  de:
  es:
  fr:
  pl: 
  ro: 
  tr:
``` 

We hebben vertalingen nodig zodat de arabische tot en met turkse zinnen aangevuld zijn en gelijk lopen met de nederlandse en engelse tekst.
